P8105 Homework 2
================
Chengshun Zhao
2026-10-07

\#Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
subway_df = read_csv(
  "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv"
)
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
subway_df = subway_df |>
  janitor::clean_names() |>
  select(
    line, station_name,
    station_latitude, station_longitude,
    starts_with("route"),
    entry, vending, entrance_type, ada
  ) |>
  mutate(
    entry = entry == "YES"
  )
```

``` r
dim(subway_df)
```

    ## [1] 1868   19

``` r
n_distinct_stations = subway_df |>
  distinct(line, station_name) |>
  nrow()

n_distinct_stations
```

    ## [1] 465

``` r
n_ada_stations = subway_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()

n_ada_stations
```

    ## [1] 84

``` r
entry_proportion = subway_df |>
  filter(vending == "NO") |>
  summarize(proportion = mean(entry))

entry_proportion
```

    ## # A tibble: 1 × 1
    ##   proportion
    ##        <dbl>
    ## 1      0.377

``` r
unique(subway_df$vending)
```

    ## [1] "YES" "NO"

Among station entrances/exits without vending, approximately 37.7% allow
entry.

``` r
route_df = subway_df |>
  mutate(across(route1:route11, as.character)) |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name"
  )

a_train_stations = route_df |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()

a_train_stations
```

    ## [1] 60

``` r
a_train_ada = route_df |>
  filter(route_name == "A", ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()

a_train_ada
```

    ## [1] 17

The subway dataset contains 1868 observations and 19 variables.
Variables include subway line and station names, longitude and latitude
of stations, routes served, station entrance status, availability of
vending machines, type of station entrance, and if the station is ADA
compliant. I converted the entry variable from character values (“YES”
or “NO”) to logical values, and select the variables to be included in
the analysis. The dataset is not fully tidy, as the routes served are
stored in multiple columns (route1 through route11). The routes should
be stored as separate variables from the number and name of the routes.

There are 60 distinct stations that serve the A train. Of these
stations, 17 are ADA compliant.

\#Problem 2

``` r
library(readxl)

excel_sheets("data/202610 Trash Wheel Collection Data.xlsx")
```

    ## [1] "Mr. Trash Wheel"                 "Professor Trash Wheel"          
    ## [3] "Captain Trash Wheel"             "Gwynnda the Good Wheel of the W"
    ## [5] "Sampling Methodology"            "Homes powered note"

``` r
mr_trash = read_excel(
  "data/202610 Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N1000"
) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )

dim(mr_trash)
```

    ## [1] 740  15

``` r
head(mr_trash)
```

    ## # A tibble: 6 × 15
    ##   dumpster month year  date                weight_tons volume_cubic_yards
    ##      <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ## 1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ## 2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ## 3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ## 4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ## 5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ## 6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

``` r
prof_trash = read_excel(
  "data/202610 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",
  range = "A2:M1000"
) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    trash_wheel = "Professor Trash Wheel"
  )

dim(prof_trash)
```

    ## [1] 137  14

``` r
gwynnda = read_excel(
  "data/202610 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynnda the Good Wheel of the W",
  range = "A2:M1000"
) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    trash_wheel = "Gwynnda"
  )
```

    ## New names:
    ## • `` -> `...13`

``` r
dim(gwynnda)
```

    ## [1] 392  14

``` r
mr_trash = mr_trash |>
  mutate(
    year = as.numeric(year),
    across(plastic_bottles:wrappers, as.numeric)
  )

prof_trash = prof_trash |>
  mutate(
    year = as.numeric(year),
    across(plastic_bottles:wrappers, as.numeric)
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `across(plastic_bottles:wrappers, as.numeric)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

``` r
gwynnda = gwynnda |>
  mutate(
    year = as.numeric(year),
    across(plastic_bottles:wrappers, as.numeric)
  )

trash_data = bind_rows(
  mr_trash,
  prof_trash,
  gwynnda
)

dim(trash_data)
```

    ## [1] 1269   16

``` r
prof_total_weight = trash_data |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarize(total_weight = sum(weight_tons, na.rm = TRUE))

prof_total_weight
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         295.

``` r
gwynnda_june_2022 = trash_data |>
  filter(
    trash_wheel == "Gwynnda",
    year == 2022,
    month == "June"
  ) |>
  summarize(total_butts = sum(cigarette_butts, na.rm = TRUE))

gwynnda_june_2022
```

    ## # A tibble: 1 × 1
    ##   total_butts
    ##         <dbl>
    ## 1       18120

The merged Trash Wheel dataset comprises 1269 observations and 16
variables. The key variables in the dataset include the number of
dumpsters, month, year, date, weight in tons, volume in cubic yards,
plastic bottles, cigarette butts and the name of the Trash Wheel.
According to the data collected by Professor Trash Wheel, a total of
214.96 tons of trash was collected. In June 2022, Gwynnda collected a
total of 18,120 cigarette butts.

\#Problem 3

``` r
baseline_df = read_csv(
  "data/MCI_baseline.csv",
  skip = 1,
  na = "."
) |>
  janitor::clean_names()
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(baseline_df)
```

    ## # A tibble: 6 × 6
    ##      id current_age   sex education apoe4 age_at_onset
    ##   <dbl>       <dbl> <dbl>     <dbl> <dbl>        <dbl>
    ## 1     1        63.1     0        16     1         NA  
    ## 2     2        65.6     0        20     1         NA  
    ## 3     3        62.5     1        16     1         66.8
    ## 4     4        69.8     0        16     0         NA  
    ## 5     5        66       1        16     0         68.7
    ## 6     6        62.5     1        16     0         NA

``` r
names(baseline_df)
```

    ## [1] "id"           "current_age"  "sex"          "education"    "apoe4"       
    ## [6] "age_at_onset"

``` r
dim(baseline_df)
```

    ## [1] 483   6

``` r
baseline_df = baseline_df |>
  mutate(
    sex = factor(
      sex,
      levels = c(0, 1),
      labels = c("Female", "Male")
    ),
    apoe4 = factor(
      apoe4,
      levels = c(0, 1),
      labels = c("Non-carrier", "Carrier")
    )
  )

head(baseline_df)
```

    ## # A tibble: 6 × 6
    ##      id current_age sex    education apoe4       age_at_onset
    ##   <dbl>       <dbl> <fct>      <dbl> <fct>              <dbl>
    ## 1     1        63.1 Female        16 Carrier             NA  
    ## 2     2        65.6 Female        20 Carrier             NA  
    ## 3     3        62.5 Male          16 Carrier             66.8
    ## 4     4        69.8 Female        16 Non-carrier         NA  
    ## 5     5        66   Male          16 Non-carrier         68.7
    ## 6     6        62.5 Male          16 Non-carrier         NA

``` r
baseline_mci = baseline_df |>
  filter(!is.na(age_at_onset), age_at_onset <= current_age)

baseline_mci
```

    ## # A tibble: 4 × 6
    ##      id current_age sex    education apoe4       age_at_onset
    ##   <dbl>       <dbl> <fct>      <dbl> <fct>              <dbl>
    ## 1    72        62.9 Male          16 Carrier             62.5
    ## 2   234        66.7 Male          18 Non-carrier         66.7
    ## 3   283        69   Male          16 Non-carrier         68.3
    ## 4   380        70.3 Female        16 Non-carrier         70.2

``` r
baseline_df = baseline_df |>
  filter(is.na(age_at_onset) | age_at_onset > current_age)

dim(baseline_df)
```

    ## [1] 479   6

``` r
baseline_summary = baseline_df |>
  summarize(
    participants = n(),
    developed_mci = sum(!is.na(age_at_onset)),
    mean_baseline_age = mean(current_age)
  )

baseline_summary
```

    ## # A tibble: 1 × 3
    ##   participants developed_mci mean_baseline_age
    ##          <int>         <int>             <dbl>
    ## 1          479            93              65.0

``` r
female_apoe4 = baseline_df |>
  filter(sex == "Female") |>
  summarize(
    proportion = mean(apoe4 == "Carrier")
  )

female_apoe4
```

    ## # A tibble: 1 × 1
    ##   proportion
    ##        <dbl>
    ## 1        0.3

After importing and cleaning the baseline demographic data, sex and
APOE4 carrier status were transformed to categorical variables. Four
participants, who developed MCI at or before baseline and, therefore,
did not meet the study inclusion criteria, were removed. The analysis
was performed on the 479 participants. Of these participants, 93
developed MCI at some point during the follow-up. The average age at
baseline was approximately 65.03 years. Of the women in the study, 30%
were APOE4 carriers.

``` r
amyloid_df = read_csv(
  "data/mci_amyloid.csv",
  skip = 1,
  na = "."
) |>
  janitor::clean_names()
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(amyloid_df)
```

    ## # A tibble: 6 × 6
    ##   study_id baseline    time_2      time_4      time_6      time_8     
    ##      <dbl> <chr>       <chr>       <chr>       <chr>       <chr>      
    ## 1        1 0.1105487   NA          0.109325197 0.104756131 0.107257697
    ## 2        2 0.107481183 0.109157373 0.109457839 0.105729713 0.10661845 
    ## 3        3 0.106087034 0.108744509 0.106065035 NA          0.106152357
    ## 4        4 0.109251358 0.108699686 0.110540386 0.107476797 0.111212209
    ## 5        5 0.107950408 0.112273883 0.115139677 0.106606054 0.106052066
    ## 6        6 0.112426974 0.112853415 0.11143945  0.110279277 0.114982747

``` r
names(amyloid_df)
```

    ## [1] "study_id" "baseline" "time_2"   "time_4"   "time_6"   "time_8"

``` r
dim(amyloid_df)
```

    ## [1] 487   6

``` r
amyloid_long = amyloid_df |>
  pivot_longer(
    baseline:time_8,
    names_to = "visit",
    values_to = "amyloid"
  )

head(amyloid_long)
```

    ## # A tibble: 6 × 3
    ##   study_id visit    amyloid    
    ##      <dbl> <chr>    <chr>      
    ## 1        1 baseline 0.1105487  
    ## 2        1 time_2   NA         
    ## 3        1 time_4   0.109325197
    ## 4        1 time_6   0.104756131
    ## 5        1 time_8   0.107257697
    ## 6        2 baseline 0.107481183

``` r
dim(amyloid_long)
```

    ## [1] 2435    3

``` r
sum(is.na(amyloid_long$amyloid))
```

    ## [1] 0

``` r
n_distinct(amyloid_long$study_id)
```

    ## [1] 487

``` r
baseline_only = baseline_df |>
  anti_join(amyloid_long, by = c("id" = "study_id")) |>
  distinct(id)

amyloid_only = amyloid_long |>
  anti_join(baseline_df, by = c("study_id" = "id")) |>
  distinct(study_id)

baseline_only
```

    ## # A tibble: 8 × 1
    ##      id
    ##   <dbl>
    ## 1    14
    ## 2    49
    ## 3    92
    ## 4   179
    ## 5   268
    ## 6   304
    ## 7   389
    ## 8   412

``` r
amyloid_only
```

    ## # A tibble: 16 × 1
    ##    study_id
    ##       <dbl>
    ##  1       72
    ##  2      234
    ##  3      283
    ##  4      380
    ##  5      484
    ##  6      485
    ##  7      486
    ##  8      487
    ##  9      488
    ## 10      489
    ## 11      490
    ## 12      491
    ## 13      492
    ## 14      493
    ## 15      494
    ## 16      495

``` r
combined_df = baseline_df |>
  inner_join(
    amyloid_long,
    by = c("id" = "study_id")
  )

dim(combined_df)
```

    ## [1] 2355    8

``` r
head(combined_df)
```

    ## # A tibble: 6 × 8
    ##      id current_age sex    education apoe4   age_at_onset visit    amyloid    
    ##   <dbl>       <dbl> <fct>      <dbl> <fct>          <dbl> <chr>    <chr>      
    ## 1     1        63.1 Female        16 Carrier           NA baseline 0.1105487  
    ## 2     1        63.1 Female        16 Carrier           NA time_2   NA         
    ## 3     1        63.1 Female        16 Carrier           NA time_4   0.109325197
    ## 4     1        63.1 Female        16 Carrier           NA time_6   0.104756131
    ## 5     1        63.1 Female        16 Carrier           NA time_8   0.107257697
    ## 6     2        65.6 Female        20 Carrier           NA baseline 0.107481183

``` r
write_csv(combined_df, "data/mci_amyloid_clean.csv")
```

The baseline dataset included 479 participants after removing 4
participants with MCI at baseline. Among the 479 participants, 93
developed MCI over the course of the study. The average age at baseline
was 65.03 years. Thirty percent of the women were APOE4 carriers. The
amyloid dataset contained 487 participants. This dataset was converted
to long format and resulted in 5 observations per participant. There
were 8 participants in the baseline dataset and 16 participants in the
amyloid dataset only. Keeping only the participants in both datasets
resulted in 471 participants, 2355 observations, and 8 variables.
